from ml import *

def main():
    keywords = \
    [
        'NTSTATUS',
        'LPC_STATUS',
        'BYTE',
        'PBYTE',
        'LARGE_INTEGER',
        'ULARGE_INTEGER',
        'va_list',
        'CHAR',
        'WCHAR',
        'MSG',
        'WSADATA',
        'WSABUF',
        'SIZE_T',
        'SizeT',
        'LPSTR',
        'LPCSTR',
        'LPWSTR',
        'LPCWSTR',
        'BOOL',
        'SOCKET',
        'WPARAM',
        'LPARAM',
        'HANDLE',
        'ULONG',
        'PULONG',
        'ULONG_PTR',
        'PULONG_PTR',
        'LONG',
        'PLONG',
        'LONG_PTR',
        'PLONG_PTR',
        'INT',
        'INT_PTR',
        'WORD',
        'DWORD',
        'PDWORD',
        'LPDWORD',
        'INT32',
        'UINT',
        'UINT32',
        'VOID',
        'PVOID',
        'LPVOID',
        'HDC',
        'HWND',
        'PHANDLE',
        'HMODULE',
        'void',
        'struct',
        'union',
        'enum',
        'char',
        'short',
        'int',
        'long',
        'double',
        'float',
        'signed',
        'unsigned',
        'const',
        'static',
        'extern',
        'auto',
        'register',
        'volatile',
        'bool',
        'class',
        'private',
        'protected',
        'public',
        'friend',
        'inline',
        'template',
        'virtual',
        'asm',
        'explicit',
        'typename',
        'mutable',
    ]

    kwlist = ''
    for kw in keywords:
        kwlist += kw + ' '

    open('kw.h', 'w').write('syn keyword cppType ' + kwlist.rstrip())

InvokeSafe(main)
